import i18next from "i18next";

export const strings = {
  // Common Strings
  add: "Add",
  next: "Next",
  edit: "Edit",
  view: "View",
  delete: "Delete",
  deleteTitle: "Are you sure?",
  deleteText: "You won't be able to revert this!",
  deleteIcon: "warning",
  confirmButtonColor: "red",
  cancelButtonColor: "#9FA6B2",
  confirmButtonText: "Yes, delete it!",
  deleteConfirmMessage: "Deleted!",
  deleteMessage: "Your file has been deleted.",
  deleteSuccess: "success",
  submit: "Submit",
  preview: "Preview",
  back: "Back",
  cancel: "Cancel",
  import: "Import",
  reset: "Reset",
  remove: "Remove",
  discard: "Discard",
  actionsField: "actions",
  actionsName: "Actions",
  alphabetsAllowed: "Only alphabets are allowed",
  status: "status",
  statusLabel: "Status",
  variant: "standard",
  export: "Export",
  profile: "Profile",
  logout: "Logout",
  noDataFound: "No Data Found",
  allowedImageExtension: "Allowed PNG, JPG and JPEG. Max size of 1.2 Mb.",
  maxImageSize: "File size too large, max file size is 1.2 Mb.",

  // Sidebar Titles
  dashboard: "Dashboard",
  productSectionTitle: "Product Management",
  categoryTitle: "Category",
  subCategoryTitle: "Sub Category",
  brandTitle: "Brand",
  productTitle: i18next.t("Product"),
  ordersTitle: "Orders",
  mediaTitle: "Media",
  officeSectionTitle: "Office Management",
  employeeTitle: "Employee",
  rolesPermissionsTitle: "Roles & Permissions",
  rolesTitle: "Roles",
  permissionsTitle: "Permissions",
  expensesTitle: "Expenses",
  expensesCategoryTitle: "Expense Category",
  expenseTitle: "Expenses",
  inquiryTitle: "Inquiry",
  followUpTitle: "Follow Up",
  accountTitle: "Account",
  bankTitle: "Bank",
  companyTitle: "Company",
  paymentMethodTitle: "Payment Method",
  taxTitle: "Tax",
  monthlyTargetTitle: "Monthly Target",
  customerSectionTitle: "Customer Management",
  customerTitle: "Customer",
  serviceInstallationTitle: "Service/Installation",
  taskTitle: "Task",
  staticTitle: "Static",
  quotationTitle: "Quotation",
  settingsTitle: "Settings",
  wareHouse: "wareHouse",
  accountant: "Accountant",
  attendanceTitle: "Attendance",
  attendanceListTitle: "Attendance List",

  // Permissions
  permissionsFieldName: "name",
  permissionsNameHeaderName: "Module Name",
  permissionsAssignedToFieldName: "assignedTo",
  permissionsAssignedToHeaderName: "Assigned To",
  permissionsListTitle: "Permissions List",
  permissionsListSubTitle:
    "  Each category (Basic, Professional, and Business) includes the four predefined roles shown below.",

  // Roles
  rolesListTitle: "Roles List",
  rolesSubTitle:
    "A role provided access to predefined menus and features so that depending on assigned role an administrator can have access to what he need",
  rolesDetailsTitle: "Total users with their roles",
  rolesDetailsSubTitle:
    "Find all of your company’s administrator accounts and their associate roles.",
  roleFieldFirstName: "first_name",
  roleHeaderFirstName: "First Name",
  roleFieldLastName: "last_name",
  roleHeaderLastName: "Last Name",
  roleFieldEmail: "email",
  roleHeaderEmail: "Email",
  roleFieldAddress: "permanent_address",
  roleHeaderAddress: "Address",
  roleFieldAdhaarCard: "adharcard_no",
  roleHeaderAdhaarCard: "Adhaar Card No.",
  roleFieldPhone: "phone",
  roleHeaderPhone: "Phone",
  editRole: "Edit Role",
  addRole: "Add Role",
  addRoleSubTitle: "Add role, if it doesnt exist.",
  total: "Total",
  user: "user",
  users: "users",
  superAdmin: "Super Admin",
  roleName: "name",
  roleNameRequired: "Role is required",
  roleLabel: "Role Name",
  roleNamePlaceholder: "Enter Role Name",
  rolesPermissions: "Role Permissions",
  setRolesPermissions: "Set Role Permissions",
  administratorAccess: "Administrator Access",
  selectAll: "Select All",
  read: "Read",
  write: "Write",
  update: "Update",
  delete: "Delete",

  // Brand
  brandSearchPlaceholder: "Search Brand",
  brandFieldName: "name",
  brandName: "Brand Name",
  addBrand: "Add Brand",
  brand: "brandName",
  brandRequired: "Brand is required",
  brandLabel: "Brand",
  brandPlaceholder: "Samsung",
  editBrand: "Edit Brand",
  viewBrand: "View Brand",

  // Category
  categorySearchPlaceholder: "Search Category",
  categoryFieldName: "name",
  categoryName: "Category Name",
  addCategory: "Add Category",
  category: "categoryName",
  categoryRequired: "Category is required",
  categoryLabel: "Category",
  categoryPlaceholder: "A.C.",
  editCategory: "Edit Category",
  viewCategory: "View Category",

  // Sub-Category
  subCategorySearchPlaceholder: "Search SubCategory",
  subCategoryFieldName: "name",
  subCategoryHeaderName: "SubCategory Name",
  subCategoryName: "Brand Name",
  addSubCategory: "Add Sub Category",
  subCategory: "subCategoryName",
  subCategoryRequired: "Sub Category is required",
  subCategoryLabel: "Sub Category",
  subCategoryPlaceholder: "Samsung",
  editSubCategory: "Edit SubCategory",
  viewSubCategory: "View SubCategory",

  // Product
  variantTitleFieldName: "Add Field Name",
  variantContentText:
    "To add product variant you should provide variant field name",
  variantLabel: "Variant Field Name",
  addProductTitle: "Add Product",
  editProductTitle: "Edit Product",
  productName: "name",
  productRequired: "Product Name is required",
  productLabel: "Product Name",
  stockName: "stock",
  stockLabel: "Stock",
  quantityRequired: "Quantity is required",
  quantityLabel: "Quantity",
  quantityPlaceholder: "5",
  categoryId: "category_id",
  subCategoryId: "subcategory_id",
  brandId: "brand_id",
  basePrice: "base_price",
  basePriceRequired: "Base Price is required",
  basePriceLabel: "Base Price",
  pricePlaceholder: "1500",
  sellPrice: "sell_price",
  sellPriceRequired: "Selling Price is required",
  sellPriceLabel: "Selling Price",
  hsnCode: "hsn_code",
  hsnCodeRequired: "HSN Code is required",
  alphabetsAndNumbersAllowed: "Only alphabets and numbers are allowed",
  hsnCodeLabel: "HSN Code",
  productTaxFieldName: "tax_id",
  productTaxFieldReqMsg: "Tax is required",
  productTaxLabelName: "Tax",
  hsnCodePlaceholder: "1234",
  skuCode: "sku_code",
  skuCodeRequired: "SKU Code is required",
  skuCodeLabel: "SKU Code",
  skuCodePlaceholder: "ABCD1234",
  description: "description",
  descriptionRequired: "Description is required",
  descriptionLabel: "Product Description",
  descriptionPlaceholder: "Description",
  productVariantTitle: "Product Variant",
  addVariantField: "Add Field",
  addVariant: "Add Variant",
  productImages: "Product Images",
  variantRequired: "Variant is required.",
  productImageRequired: "Product Image is required.",
  productMainImage: "productImage",
  uploadProductMainImage: "Upload Product Main Image",
  productSubImageRequired: "Product Sub Image is required.",
  productSubImage: "image",
  uploadProductSubImages: "Upload Product Sub Images",
  searchProduct: "Search Product",
  addMultipleProduct: "Add Multiple Product",
  productExcelFile: "productFile",
  uploadMultipleProducts: "Upload Multiple Products",
  excelRequired: "Excel is required.",
  productViewTitle: "Product View",
  productImagesTitle: "Product Image:",
  productSubImagesTitle: "Product Sub Images:",
  productNameTitle: "Product Name:",
  productQuantityTitle: "Quantity:",
  productCategoryTitle: "Category:",
  productSubCategoryTitle: "SubCategory:",
  productBrandTitle: "Brand:",
  productBasePriceTitle: "Base Price:",
  productSellingPriceTitle: "Selling Price:",
  productSKUCodeTitle: "SKU Code:",
  productHSNCodeTitle: "HSN Code:",
  productTaxTitle: "Tax:",
  productDescriptionTitle: "Description:",
  productVariantsTitle: "Variants:",

  // Employee
  employeeVariant: "contained",
  employeeSearchPlaceholder: "Search",
  employeeFieldFirstName: "first_name",
  employeeFieldMiddleName: "middle_name",
  employeeLabelMiddleName: "Middle Name",
  employeeFieldLastName: "last_name",
  employeeLabelLastName: "Last Name",
  employeeFieldEmail: "email",
  employeeLabelEmail: "Email",
  employeeFieldAlternatePhone: "alternate_phone",
  employeeLabelAlternatePhone: "Alternate Phone",
  employeeFieldPermanentAddress: "permanent_address",
  employeeLabelPermanentAddress: "Permanent Address",
  employeeFieldPresentAddress: "present_address",
  employeeLabelPresentAddress: "Present Address",
  employeeFieldRoleName: "role",
  employeeLabelRoleName: "Role Name",
  employeeFirstName: "Employee Name",
  employeeFieldPhone: "phone",
  employeePhone: "Phone",
  employeeAdharCardNo: "Aadhar Card No.",
  employeeFieldAdharNo: "adharcard_no",
  employeeEditTitle: "Edit Employee Details",
  employeeAddTitle: "Add Employee Details",

  employeeFirstNameMessage: "First Name is required",
  employeeFirstNameMinLength: "First Name must be minimum 3 characters",
  employeeFirstNameLabel: "First Name",
  employeeFirstNamePlaceholder: "Enter your first name",

  employeeFieldMiddleName: "middle_name",
  employeeMiddleNameMinLength: "Middle Name must be minimum 3 characters",
  employeeMiddleNameLabel: "Middle Name",
  employeeMiddleNamePlaceholder: "Enter your middle name",

  employeeFieldLastName: "last_name",
  employeeLastNameMinLength: "Last Name must be minimum 3 characters",
  employeeLastNameMessage: "Last Name is required",
  employeeLastNameLabel: "Last Name",
  employeeLastNamePlaceholder: "Enter your last name",

  employeePresentAddress: "present_address",
  employeePresentAddressMinLength: "Address must be minimum 5 characters",
  employeePresentAddressMessage: "Address is required",
  employeePresentAddressLabel: "Present Address",
  employeePresentAddressPlaceholder: "Enter your Address",

  employeePermanentAddress: "permanent_address",
  employeePermanentAddressMinLength: "Address must be minimum 5 characters",
  employeePermanentAddressMessage: "Permanent address is required",
  employeePermanentAddressLabel: "Permanent Address",
  employeePermanentAddressPlaceholder: "Enter your permanent address",

  employeeFieldPhone: "phone",
  employeePhoneMessage: "Contact No is required",
  employeePhoneLabel: "Contact Number",
  employeePhonePlaceholder: "9876543210",

  employeeFieldAlternatePhone: "alternate_phone",
  employeeAlternatePhoneLabel: "Alternate Number",
  employeeAlternatePhonePlaceholder: "9876543210",

  employeeFieldEmail: "email",
  employeeEmailLabel: "Email id",
  employeeEmailMessage: "Email is required",
  employeeEmailPatternMessage: "Email is Not Valid",
  employeeEmailPlaceholder: "example@gmail.com",

  employeeFieldPassword: "password",
  employeePasswordMessage: "Password is required",
  employeePasswordMinLength: "Weak password",
  employeePasswordPatternMessage:
    "Password must include 1 lowercase, 1 uppercase, a number, 8 characters and a special character.",
  employeePasswordMaxLength: "Password is too long",
  employeePasswordLabel: "Password",

  employeeFieldRole: "rol_u_id",
  employeeRoleLabel: "Role",
  employeeRoleMessage: "Role is required",

  employeeFieldAdharCard: "adharcard_no",
  employeeAdharCardMinLength: "Adhar card number is not valid",
  employeeAdharCardMessage: "Adhaar Card Number is required",
  employeeAdharCardLabel: "Adharcard Number",
  employeeAdharCardPlaceholder: "7856 4564 6565",

  employeeImage: "image",
  employeeIdImage: "id_image",
  employeeUploadUserImage: "Upload User Image",
  employeeUploadIdProof: " Upload Id Proof",
  employeeImageRequired: " Image is required.",

  employeeUserViewLeftText: "1.23k",
  employeeUserViewLeftTaskDone: "Task Done",
  employeeUserViewLeftNumber: "568",
  employeeUserViewLeftProjectDone: "Project Done",
  employeeUserViewFullName: "Full Name:",
  employeeUserViewLeftEmail: "Email:",
  employeeUserViewLeftAddress: "Present Address:",
  employeeUserViewLeftPermanentAddress: "Permanent Address:",
  employeeUserViewLeftContact: "Contact:",
  employeeUserViewLeftAlternateContact: "Alternate Contact:",
  employeeUserViewLeftAdharCard: "Adhaar Card No.:",

  employeeNotificationText:
    " You will receive notification for the below selected items.",
  employeeNotificationType: "Type",
  employeeNotificationEmail: "Email",
  employeeNotificationBrowser: "Browser",
  employeeNotificationApp: "App",
  employeeNotificationNewForYou: "New for you",
  employeeNotificationAccount: "Account activity",
  employeeNotificationNewBrowser: "A new browser used to sign in",
  employeeNotificationDevice: "A new device is linked",
  employeeNotificationSaveChanges: "Save Changes",
  employeeNotificationDiscard: "Discard",

  employeeOverViewTitle: "Project List",
  employeeOverViewProject: "Project",
  employeeOverViewTask: "Total Task",
  employeeOverViewProgress: "Progress",
  employeeOverViewHours: "Hours",
  employeeOverViewUserTitle: "User Activity Timeline",
  employeeOverViewInvoices: "12 Invoices have been paid",
  employeeOverViewMin: "12 min ago",
  employeeOverViewCompany: "Invoices have been paid to the company",
  employeeOverViewPdf: "invoice.pdf",
  employeeOverViewJohn: "Meeting with John",
  employeeOverViewMinAgo: "45 min ago",
  employeeOverViewReact: "React Project meeting with John @10:15am",
  employeeOverViewClient: "John Doe (Client)",
  employeeOverViewProjectMeeting: "Project meeting with John @10:15am",
  employeeOverViewProjectForClient: "Create a new react project for client",
  employeeOverViewDays: "2 days ago",
  employeeOverViewMembers: "Add 5 team members in the project",
  employeeOverViewNewProject: "Create a new project for client",
  employeeOverViewTeam: "5 team members in the project",
  employeeOverViewCreateInvoices: "Create invoices for client",
  employeeOverViewDaysAgo: "5 days ago",
  employeeOverViewWeekly:
    "Weekly review of freshly prepared design for our new app.",

  employeeViewSecurityTitle: "Change Password",
  employeeViewSecurityRequirements: "Ensure that these requirements are met",
  employeeViewSecurityUppercase:
    "Minimum 8 characters long, uppercase & symbol",
  employeeViewSecurityNewPassword: "New Password",
  employeeViewSecurityConfirmPassword: "Confirm New Password",
  employeeViewSecurityRecent: "Recent devices",
  employeeViewSecurityBrowser: "Browser",
  employeeViewSecurityDevice: "Device",
  employeeViewSecurityLocation: "Location",
  employeeViewSecurityActivity: "Recent Activity",

  employeeInvoiceListDownload: "Download",
  employeeInvoiceListEdit: "Edit",
  employeeInvoiceListDuplicate: "Duplicate",
  employeeInvoiceInvoiceStatus: "invoiceStatus",
  employeeInvoiceBalance: "Balance:",
  employeeInvoiceDue: "Due Date:",
  employeeInvoiceListFieldTotal: "total",
  employeeInvoiceTotal: "Total",
  employeeInvoiceListFieldIssued: "issuedDate",
  employeeInvoiceIssued: "Issued Date",
  employeeInvoiceDelete: "Delete Invoice",
  employeeInvoiceView: "View",
  employeeInvoiceList: "Invoice List",
  employeeInvoiceExport: "Export",
  employeeInvoicePDF: "PDF",
  employeeInvoiceXLSX: "XLSX",
  employeeInvoiceCSV: "CSV",

  // Expense-Category
  expenseCategory: "Search",
  expenseCategoryAdd: "Add Category",
  expenseCategoryFieldName: "name",
  expenseCategoryName: "Category Name",
  expenseCategoryEditTitle: "Edit Expense Category",
  expenseCategoryFieldCategoryName: "categoryName",
  expenseCategoryReqMessage: "Expense Category Name is required",
  expenseCategoryLabelCategoryName: "Expense Category Name",
  expenseCategoryPlaceholder: "Enter expense category",
  expenseCategoryAddTitle: "Add Expense Category",

  // Expense
  expenseAddTitle: "Add Expense",
  expenseFieldName: "name",
  expenseReqMessage: "Name is required",
  expenseLabelName: "Name",
  expenseFieldTotalCost: "total_cost",
  expenseTotalCostReqMessage: "Total Cost is required",
  expenseTotalCostMessage: "Only numbers are allowed",
  expenseTotalCostLabel: "Total Cost",
  expenseSelectCategoryLabel: "Select Category",
  expenseSelectCategoryReqMessage: "Please select category",
  expenseInputLabelName: "Select Category",
  expenseDateName: "date",
  expenseDateLabelName: "Date",
  expenseDateReqMessage: "Date is required",
  expenseDescription: "description",
  expenseDescriptionLabel: "Description",
  expenseViewEditTitle: "Expense",
  expenseSearch: "Search",
  expenseEditText: "Edit",
  expenseViewText: "View",
  expenseDeleteText: "Delete",
  expenseNoDataFound: "No Data Found",

  // Media
  mediaListTitle: "Media Folder",
  mediaAllDelete: "Delete All Media",
  mediaSelectDelete: "Delete Selected Media",
  mediaAddMediaButton: " Add Media",
  mediaAllDeleteText: "Are you sure You won't Delete All?",
  mediaSelectDeleteText: "Are you sure You won't Delete Selected Media?",
  mediaAddTitle: "Add Images",
  mediaAddImgName: "images",
  mediaAddImgNameAlt: "media delete",
  mediaAddImgBtn: "Select Single & Multiple Image",
  mediaAddImgSizeText: "File size too large, max file size is 1MB",
  mediaAddImgAllowText: "Allowed PNG, JPG and JPEG. Max size of 1MB",
  mediaAddUploadBtn: "Upload",
  mediaAddCancelBtn: "Cancel",

  // Static-page
  staticAddTitle: "Add Static Page",
  staticAddBtn: "Add Static-Page",
  staticFieldName: "name",
  staticHeaderName: "name",
  staticFieldSlug: "slug",
  staticHeaderNameSlug: "Link",
  staticViewTitle: "View Static Details",
  staticViewBackBtn: "Back",
  staticEditTitle: "Edit Static Page",
  staticEditName: "details",
  staticEditNameRules: "Description is required",
  staticEditNameTitle: "title",
  staticEditNameTitleRules: "Name is required",
  staticEditNameTitleLabel: "Name",
  staticEditNameTitlePlaceHolder: "Name",
  staticEditSlugTitle: "slug",
  staticEditSlugTitleRules: "slug is required",
  staticEditSlugTitleLabel: "Slug",
  staticEditSlugTitlePlaceholder: "slug",
  staticEditCancelBtn: "Cancel",

  // Customer List
  customerColumnFirstNameFiled: "first_name",
  customerColumnFirstNameHeaderName: "First Name",
  customerColumnLastNameFiled: "last_name",
  customerColumnLastNameHeaderName: "Last Name",
  customerColumnCustomerTypeFiled: "customer_type",
  customerColumnCustomerTypeHeaderName: "Customer Type",
  customerColumnAlternatePhoneFiled: "alternate_phone",
  customerColumnAlternatePhoneHeaderName: "Alternate Phone",
  customerColumnOtpFiled: "otp",
  customerColumnOtpHeaderName: "Otp",
  customerColumnEmailFiled: "email",
  customerColumnEmailHeaderName: "Email",
  customerColumnPhoneNoFiled: "phone",
  customerColumnPhoneNoHeaderName: "Phone No",

  // Customer Edit
  customerEditTitle: "Edit Customer Details",

  customerEditFirstName: "first_name",
  customerEditFirstNameLabel: "First Name",
  customerEditFirstNameRequire: "First Name is required",
  customerEditFirstNameMinLength: "First Name must be minimum 3 characters",
  customerEditFirstNamePatternMsg: "Only alphabets allowed",
  customerEditFirstNameTrigger: "name",
  customerEditFirstNamePlaceholder: "First Name",
  customerEditFirstNameAriaDescribedby: "name",
  customerEditFirstNameId: "name",

  customerEditLastName: "last_name",
  customerEditLastNameLabel: "Last Name",
  customerEditLastNameRequire: "Last Name is required",
  customerEditLastNameMinLength: "Last Name must be minimum 3 characters",
  customerEditLastNamePatternMsg: "Only alphabets allowed",
  customerEditLastNameTrigger: "last_name",
  customerEditLastNamePlaceholder: "Last Name",
  customerEditLastNameAriaDescribedby: "last_name",
  customerEditLastNameId: "last_name",

  customerEditPhone: "phone",
  customerEditPhoneLabel: "Phone Number",
  customerEditPhoneRequire: "Phone No is required",
  customerEditPhonePatternMsg: "Only numbers allowed",
  customerEditPhoneTrigger: "phone",
  customerEditPhonePlaceholder: "9876543210",
  customerEditPhoneAriaDescribedby: "phone",
  customerEditPhoneId: "phone",

  customerEditAlternateNumber: "alternate_phone",
  customerEditAlternateNumberLabel: "Alternate Number",
  customerEditAlternateNumberPlaceholder: "optional",
  customerEditAlternateNumberAriaDescribedby: "alternate_phone",
  customerEditAlternateNumberId: "alternate_phone",

  customerEditEmail: "email",
  customerEditEmailLabel: "Email",
  customerEditEmailRequire: "Email is required",
  customerEditEmailPatternMsg: "Email is Not Valid",
  customerEditEmailTrigger: "email",
  customerEditEmailPlaceholder: "user@gmail.com",
  customerEditEmailAriaDescribedby: "email",
  customerEditEmailId: "email",

  customerEditCustomerTypeInput: "Customer Type",
  customerEditCustomerTypeHtmlForInput: "customer_type",
  customerEditCustomerTypeIdInput: "customer_type",

  customerEditCustomerType: "customer_type",
  customerEditCustomerTypeLabel: "Customer Type",
  customerEditCustomerTypeRequire: "Customer Type is required",
  customerEditCustomerTypeAriaDescribedby: "customer_type",
  customerEditCustomerTypeId: "customer_type",
  customerEditCustomerTypeValueOne: "Residential",
  customerEditCustomerTypeValueTwo: "Commercial",

  customerEditStatus: "status",
  customerEditStatusLabel: "Status",

  // Customer view-left
  customerViewLeftTitle: "Details",
  customerViewLeftUserName: "Username:",
  customerViewLeftEmail: "Email:",
  customerViewLeftCustomerType: "Customer Type:",
  customerViewLeftContact: "Contact:",
  customerViewLeftAlternateContact: "Alternate Contact:",
  customerViewLeftStatus: "Status:",

  // Customer View-order
  customerOrderViewTitle: "Order List",
  customerOrderViewOrderDate: "Order Date",
  customerOrderViewPaymentMethod: "Payment Method",
  customerOrderViewStatus: "Status",
  customerOrderViewTotalAmount: "Total Amount",
  customerOrderViewActions: "Actions",

  // Bank
  addBankDetails: "Add Bank Details",
  editBankDetails: "Edit Bank Details",
  bank: "name",
  bankName: "bank_name",
  bankNameRequired: "Bank Name is required",
  bankNameMinCharacters: "Bank Name must be minimum 3 characters",
  bankNameLabel: "Bank Name",
  bankNamePlaceholder: "Please Enter Bank Name",
  branch: "branch",
  branchRequired: "Branch Name is required",
  branchMinCharacters: "Branch Name must be minimum 3 characters",
  branchLabel: "Branch",
  branchPlaceholder: "ANAND BRANCH",
  accountNo: "account_no",
  accountNoRequired: "Account Number is required",
  minimumAccountNo: "Account Number must be of 9 numbers",
  maximumAccountNo: "Account Number cant be more than 20 numbers",
  accountNoLabel: "Account Number",
  accountNoPlaceholder: "8642086420",
  ifscCode: "ifsc_code",
  ifscCodeRequired: "IFSC Code is required",
  minimumIfscCode: "IFSC Code must be of 11 characters",
  maximumIfscCode: "IFSC Code cant be more than 25 characters",
  ifscCodeValid: "Please enter valid IFSC Code",
  ifscCodeLabel: "IFSC Code",
  ifscCodePlaceholder: "SBISPU123456",
  upiIdCode: "upi_id",
  upiIdRequired: "UPI ID is required",
  upiIdValid: "Please enter valid UPI ID",
  upiIdLabel: "UPI ID",
  upiIdPlaceholder: "sbi@95674848484",
  qrCodeImage: "qr_code_image",
  qrCodeImageRequired: "QR Code is required.",
  uploadQrCodeImage: "Upload QR Code Image",
  searchBank: "Search Bank",
  addBank: "Add Bank",
  bankNameTitle: "Bank Name:",
  branchTitle: "Branch:",
  accountNoTitle: "Account Number:",
  ifscCodeTitle: "IFSC Code:",
  upiIdTitle: "UPI ID:",

  // Company
  addCompanyDetails: "Add Company Details",
  editCompanyDetails: "Edit Company Details",
  companyName: "name",
  companyRequired: "Company Name is required",
  companyMinCharacters: "Company Name must be minimum 3 characters",
  companyNameLabel: "Company Name",
  companyNamePlaceholder: "Lawsuit",
  firstPerson: "first_person",
  companyPersonRequired: "Company Person Name is required",
  companyPersonMinCharacters:
    "Company Person Name must be minimum 3 characters",
  companyPersonNameLabel: "Person Name",

  companyContactNo: "contact_no",
  companyContactNoRequired: "Contact Number is required",
  companyContactNoLabel: "Contact Number",

  companyAddress: "address",
  companyAddressRequired: "Address is required",
  companyAddressValid: "Address is not valid",
  companyAddressLabel: "Address",

  companyLogo: "logo",
  companyLogoRequired: "Logo is required",
  uploadCompanyLogo: "Upload Company Logo",
  companyNameTitle: "Company Name:",
  companyPersonNameTitle: "Company Person Name:",
  companyAddressTitle: "Address:",
  companyContactTitle: "Contact:",
  companyStatusTitle: "Status:",
  companySearch: "Search",

  // Payment-Method
  paymentSearch: "Search Payment",
  addPaymentType: "Add Payment Type",
  editPaymentType: "Edit Payment Type",
  paymentName: "name",
  paymentLabel: "Payment Type",
  paymentPlaceholder: "Enter Payment Type",
  paymentMethodRequired: "Payment Type is required",

  // Tax
  addTaxDetails: "Add Tax Details",
  editTaxDetails: "Edit Tax Details",
  taxName: "name",
  taxNameRequired: "Tax Name is required",
  taxNameLabel: "Tax Name",
  taxPercentage: "percentage",
  taxPercentageRequired: "Percentage is required",
  taxPercentageValid:
    "Percentage must include 1 number and % special character.",
  taxPercentageLabel: "Percentage",
  taxSearch: "Search",

  // Profile
  profile: "Profile",
  profileFirstName: "first_name",
  profileFirstLabel: "First Name",
  profileMiddleName: "middle_name",
  profileMiddleLabel: "Middle Name",
  profileLastName: "last_name",
  profileLastLabel: "Last Name",
  profilePhone: "phone",
  profilePhoneLabel: "Contact Number",
  profilePhonePlaceholder: "9876543210",
  profilePhoneValid: "Only numbers are allowed",
  profileAlternatePhone: "alternate_phone",
  profileAlternatePhoneLabel: "Alternate Number",
  profileEmail: "email",
  profileEmailLabel: "Email",
  profileEmailValid: "Email is Not Valid",
  profileEmailPlaceholder: "ranbir@gmail.com",
  profileImage: "image",
  profileUploadImage: "Upload image",

  // Quotation
  quotationTitle: "Quotation",
  quotationExistingCustomerInputTitle: "Existing Customer",
  quotationNewCustomerTitle: "New Customer",
  quotationFormFullName: "customer_name",
  quotationFormFullNameRule: "Full Name is Required",
  quotationFormFullNameLabel: "Full Name",
  quotationFormFullNameTrigger: "customer_name",
  quotationFormFullNamePlaceHolder: "Full Name",

  quotationFormPhone: "phone",
  quotationFormPhoneRule: "Phone is Required",
  quotationFormPhoneMinLength: "Phone number must be minimum of 10 digits",
  quotationFormPhoneRuleMsg: "Only numbers are allowed",
  quotationFormPhoneLabel: "Phone",
  quotationFormPhoneTrigger: "phone",
  quotationFormPhonePlaceHolder: "Phone",

  quotationFormAddress: "address",
  quotationFormAddressRule: "Address is Required",
  quotationFormAddressLabel: "Address",
  quotationFormAddressPlaceHolder: "Enter Address",

  quotationFormEmail: "email",
  quotationFormEmailRule: "Email is Required",
  quotationFormEmailRuleMsg: "Email is Not Valid",
  quotationFormEmailLabel: "Email Id",
  quotationFormEmailTrigger: "email",
  quotationFormEmailPlaceHolder: "carterleonard@gmail.com",

  quotationFormDiscount: "discount",
  quotationFormDiscountRule: "Discount is Required",
  quotationFormDiscountRuleMsg: "Email is Not Valid",
  quotationFormDiscountLabel: "Discount",
  quotationFormDiscountTrigger: "discount",
  quotationFormDiscountPlaceHolder: "10%",

  quotationFormProduct: "product",
  quotationFormProductLabel: "Product",

  quotationFormVariant: "variant",
  quotationFormVariantLabel: "Variant",
  quotationFormVariantPlaceHolder: "Variant",

  quotationFormBrand: "brand",
  quotationFormBrandLabel: "Brand",
  quotationFormBrandPlaceHolder: "Brand",

  quotationFormQuantity: "qty",
  quotationFormQuantityLabel: "Quantity",
  quotationFormQuantityPlaceHolder: "qty",

  quotationFormUnitPrice: "unit_price",
  quotationFormUnitPriceLabel: "Unit Price",
  quotationFormUnitPricePlaceHolder: "Unit Price",

  quotationForDiscountPriceUnitPrice: "discount_price",
  quotationFormDiscountPriceLabel: "Discount Price",
  quotationFormDiscountPricePlaceHolder: "Discount Price",

  quotationFormGst: "gst",
  quotationFormGstLabel: "GST Amount",
  quotationFormGstPlaceHolder: "GST Amount",

  quotationFormTax: "gst",
  quotationFormTaxLabel: "GST",
  quotationFormTaxPlaceHolder: "GST",

  quotationFormTotalPrice: "total_price",
  quotationFormTotalPriceLabel: "Total Price",
  quotationFormTotalPricePlaceHolder: "Total Price",

  // Inquiry
  inquiryListHeaderNameFirstName: "name",
  inquiryListHeaderNameField: "customer.first_name",
  inquiryListHeaderEmail: "email",
  inquiryListHeaderEmailField: "customer.email",
  inquiryListHeaderMobile: "mobile",
  inquiryListHeaderMobileField: "customer.phone",
  inquiryListHeaderCreatedBy: "created By",
  inquiryListHeaderCreatedByField: "staff.first_name",
  inquiryListAddInquiry: "Add Inquiry",

  inquiryAddTitle: "Add Inquiry Details",
  inquiryExistingCustomerLabel: "Customers Name",
  inquiryExistingCustomerPlaceholder: "Search customer details",

  inquiryAddFirstName: "first_name",
  inquiryAddFirstNameRequired: "First Name is required",
  inquiryAddFirstNameMinLength: "First Name must be minimum 3 characters",
  inquiryAddFirstNamePatten: "Only alphabets allowed",
  inquiryAddFirstNameLabel: "First Name",
  inquiryAddFirstNameTrigger: "first_name",
  inquiryAddFirstNamePlaceholder: "First Name",

  inquiryAddLastName: "last_name",
  inquiryAddLastNameRequired: "Last Name is required",
  inquiryAddLastNameMinLength: "Last Name must be minimum 3 characters",
  inquiryAddLastNamePatten: "Only alphabets allowed",
  inquiryAddLastNameLabel: "Last Name",
  inquiryAddLastNameTrigger: "last_name",
  inquiryAddLastNamePlaceholder: "Last Name",

  inquiryAddPhone: "phone",
  inquiryAddPhoneRequired: "Phone No is required",
  inquiryAddPhonePatten: "Only numbers allowed",
  inquiryAddPhoneLabel: "Phone Number",
  inquiryAddPhoneTrigger: "phone",
  inquiryAddPhonePlaceholder: "9876543210",

  inquiryAlternateNumber: "alternate_phone",
  inquiryAlternateNumberLabel: "Alternate Number",
  inquiryAlternateNumberPlaceholder: "optional",

  inquiryAddEmail: "email",
  inquiryAddEmailRequired: "Email is required",
  inquiryAddEmailPatten: "Email is Not Valid",
  inquiryAddEmailLabel: "Email",
  inquiryAddEmailTrigger: "email",
  inquiryAddEmailPlaceholder: "carterleonard@gmail.com",

  inquiryAddAddress: "billing_address",
  inquiryAddAddressRequired: "Address is required",
  inquiryAddAddressLabel: "Address",
  inquiryAddAddressTrigger: "email",
  inquiryAddAddressPlaceholder: "Enter Address",

  inquiryAddProduct: "product",
  inquiryAddProductRequired: "Product is Required",
  inquiryAddProductLabel: "Product",
  inquiryAddProductTrigger: "email",
  inquiryAddProductPlaceholder: "Enter Address",

  inquiryAddStaff: "Staff",
  inquiryAddStaffRequired: "Please Select Staff",
  inquiryAddStaffLabel: "Staff",

  inquiryAddBrand: "Brand",
  inquiryAddBrandRequired: "Brand is required",
  inquiryAddBrandLabel: "Brand",

  inquiryAddNotes: "notes",
  inquiryAddNotesRequired: "Notes is required",
  inquiryAddNotesLabel: "Requirement Note",
  inquiryAddNotesPlaceholder: "Requirement Note",

  inquiryAddTotal: "Total",
  inquiryAddTotalPlaceholder: "0.00",

  inquiryAddDiscountedPrice: "Discounted Price",
  inquiryAddProductDiscountedPrice: "10%",

  inquiryAddFinalPrice: "Final Price",
  inquiryAddProductFinalPrice: "0.00",

  inquiryAddReminderInfo: "reminder_info",
  inquiryAddReminderInfoRequired: "Reminder Info is required",
  inquiryAddReminderInfoMinLength: "Reminder Info must be minimum 3 characters",
  inquiryAddReminderInfoPatten: "Only alphabets allowed",
  inquiryAddReminderInfoLabel: "Reminder Info",
  inquiryAddReminderInfoTrigger: "reminder_info",
  inquiryAddReminderInfoPlaceholder: "Reminder Info",

  inquiryAddNotes: "requirement_description",
  inquiryAddNotesRequired: "Notes is required",
  inquiryAddNotesLabel: "Notes",
  inquiryAddNotesPlaceholder: "Enter Note",

  inquiryAddReminderDate: "reminder_date",
  inquiryAddReminderDateLabel: "Reminder date",

  inquiryViewTitle: "View Inquiry Details",
  inquiryViewCardOneTitle: "Customer Info",
  inquiryViewCardOneFirstName: "First Name",
  inquiryViewCardOneLastName: "Last Name",
  inquiryViewCardOneAddress: "Address",
  inquiryViewCardOnePhone: "Phone",
  inquiryViewCardOneAltPhone: "AlterNative Phone",
  inquiryViewCardOneEmail: "Email",

  inquiryViewCardTwoTitle: "Product Info",
  inquiryViewCardTwoBrand: "Brand",
  inquiryViewCardTwoStaff: "Staff",
  inquiryViewCardTwoDiscount: "Discount",
  inquiryViewCardTwoTotalPrice: "Total Price",
  inquiryViewCardTwoFinalPrice: "Final Price",
  inquiryViewCardTwoProduct: "Product",

  inquiryViewCardThreeTitle: "Reminder Info",
  inquiryViewCardThreeReminderNote: "Reminder Note",
  inquiryViewCardThreeReminderDate: "Reminder Date",

  // setting
  settingTitle: "Setting",
  settingCompanyLabelName: "Company Name",
  settingCompanyName: "company_name",
  settingCompanyReqMsg: "Company name is required",
  settingCompanyMsg: "Only alphabets allowed",
  settingCompanyPlaceholder: "Enter company name",

  settingCompanyAddressLabelName: "Company Address",
  settingCompanyAddress: "company_address",
  settingCompanyAddressReqMsg: "company address is required",
  settingCompanyAddressPlaceholder: "Enter company address",

  settingCompanyPhoneLabelName: "Phone",
  settingCompanyPhone: "phone",
  settingCompanyPhoneReqMsg: "Phone is required",
  settingCompanyPhonePlaceholder: "Enter phone no.",

  settingCompanyLanguageLabelName: "Language",
  settingCompanyLanguage: "language",
  settingCompanyLanguageReqMsg: "Language is required",
  settingCompanyLanguageMenuItemEng: "English",
  settingCompanyLanguageMenuItemHin: "Hindi",
  settingCompanyLanguageMenuItemGuj: "Gujarati",

  settingCompanyLatitudeLabelName: "Latitude",
  settingCompanyLatitudeName: "latitude",
  settingCompanyLatitudeReqMsg: "latitude is required",
  settingCompanyLatitudeMsg: "Only Number allowed And maximum 8 number",

  settingCompanyLongitudeLabelName: "Longitude",
  settingCompanyLongitudeName: "longitude",
  settingCompanyLongitudeReqMsg: "longitude is required",
  settingCompanyLongitudeMsg: "Only Number allowed ",

  settingCompanyOpenTimeLabelName: "Open Time",
  settingCompanyOpenTimeName: "open_time",
  settingCompanyOpenTimeReqMsg: "Open time is required",
  settingCompanyOpenTimeMsg: "Invalid Time Format",

  settingCompanyCloseTimeLabelName: "Close Time",
  settingCompanyCloseTimeName: "close_time",
  settingCompanyCloseTimeReqMsg: "Close time is required",
  settingCompanyCloseTimeMsg: "Invalid Time Format",

  settingCompanyDateFormatLabelName: "Date Format",
  settingCompanyDateFormatName: "date_format",
  settingCompanyDateFormatReqMsg: "Date Format is required",
  settingCompanyDateFormatMenuItemFirst: "dd mmm, yyyy",
  settingCompanyDateFormatMenuItemSec: "dd/mm/yyyy ",

  settingCompanyCurrencyLabelName: "Currency",
  settingCompanyCurrencyName: "currency",
  settingCompanyCurrencyReqMsg: "Currency is required",
  settingCompanyCurrencyMenuItemFirst: "INR",
  settingCompanyCurrencyMenuItemSec: "₹",

  settingCompanyCurrencyPositionLabelName: "Currency Position",
  settingCompanyCurrencyPositionName: "currency_position",
  settingCompanyCurrencyPositionReqMsg: "Currency Position is required",
  settingCompanyCurrencyPositionMenuItemFirst: "Prefix",
  settingCompanyCurrencyPositionMenuItemSec: "Suffix",

  settingCompanyLogoLabelName: "Company Logo",
  settingCompanyLogoName: "logo",
  settingCompanyLogoUploadText: "  Upload Company Logo",
  settingCompanyLogoReqMsg: "File size too large, max file size is 1 Mb",
  settingCompanyLogoMsg: " Allowed PNG, JPG and JPEG. Max size of 800K.",
  settingCompanyLogoMenuItemFirst: "Prefix",
  settingCompanyLogoMenuItemSec: "Suffix",

  settingUpdateButton: "Update",

  // forgot-password
  forgotPasswordIllustrationWrapperAltMsg: "forgot-password-illustration",
  forgotPasswordTextName: "Forgot Password? 🔒",
  forgotPasswordEmailText:
    "Enter your email and we&prime;ll send you instructions to reset your password",
  forgotPasswordEmailFieldName: "email",
  forgotPasswordEmailReqMsg: "Email is required",
  forgotPasswordEmailMsg: "This is not a valid email",
  forgotPasswordEmailLabelName: "Email",
  forgotPasswordEmailPlaceholder: "carterleonard@gmail.com",
  forgotPasswordSendResetButton: "Send reset link",
  forgotPasswordBackToLoginButton: "Back to login",

  // follow-up
  followupHistoryButton: "History",
  followupSearchPlaceholder: "Search",
  followupAddButton: "Add Follow Up",

  followupDialogSalesmanName: "Salesman Name",
  followupDialogSalesmanFieldName: "dcs_u_id",

  followupDialogCustomerName: "Customer Name",
  followupDialogCustomerNameField: "cus_u_id",

  followupDialogFollowUpDateName: "Follow Up Date",
  followupDialogFollowUpDateField: "assign_date",

  followupDialogAddSubmitButton: "Add",
  followupDialogCancelButton: "Cancel",

  followupNoDataFound: " No Data Found",

  followupSalesmanName: "Salesman Name",
  followupSalesmanFieldName: "Salesman_Name",
  followupCustomerName: "Customer Name",
  followupCustomerNameField: "customer_name",
  followupStatusName: "Status",
  followupStatusNameField: "status",
  followupReminderDateName: "Reminder Date",
  followupReminderDateNameField: "reminder_date",
  followupReminderTimeName: "Reminder Time",
  followupReminderTimeNameField: "reminder_time",
  followupHistoryDetailsText: "History Details",
  followupReasonName: "Pending Reason",
  followupReasonNameField: "pending_reason",

  // login
  loginEmailYupMsg: "Email must be a valid email",
  loginEmailYupReqMsg: "Email is required",
  loginPasswordYupReqMsg: "Password is required",
  loginPasswordYupMsg: "Weak password",
  loginSuccessToastMessage: "Login Successfully",
  loginLoadingToastMsg: "Please Wait...",
  loginIllustrationAltText: "login-illustration",
  loginTypographyText: "Please sign-in to your account and start the adventure",
  loginEmailName: "email",
  loginEmailLabelName: "Email",
  loginEmailPlaceholder: "admin@gmail.com",
  loginPasswordLabelName: "Password",
  loginPasswordName: "password",
  loginPasswordTextName: "text",
  loginForgotPasswordText: "Forgot Password?",
  loginTextButton: "Login",

  // order-management
  orderSearchPlaceholder: "Search Order",
  orderAddButton: "Add Order",
  orderIDName: "Order ID",
  orderIdFieldName: "order_id",
  orderDateName: "Order Date",
  orderDateFieldName: "order_date",
  orderPaymentMethodName: "Payment Method",
  orderPaymentMethodFieldName: "payment_method",
  orderTotalPriceName: "Total Price",
  orderTotalPriceFieldName: "total_price",
  orderStatusName: "Status",
  orderStatusFieldName: "status",
  orderActionName: "Actions",
  orderActionFieldName: "actions",

  orderViewCardOrderID: "order id:",
  orderViewCardOrderDate: "order Date:",
  orderViewCardPaymentMethod: "Payment Method:",
  orderViewCardQuantity: "Quantity :",
  orderViewCardTotalPrice: "Total Price:",

  orderEditTitle: "Edit Order",
  ordersDateNameText: "date",
  orderDateLabelNameText: "Date",
  orderDateReqMsg: "Date is required",
  orderDateMessage: "Date format - DD/MM/YYYY is allowed",

  orderStaffFieldName: "dcs_u_id",
  orderStaffLabelName: "Staff",
  orderStaffReqMsg: "Staff is required",

  orderCustomerFieldName: "cus_u_id",
  orderCustomerLabelName: "Customer",
  orderCustomerReqMsg: "Customer is required",

  orderPaymentMethodFieldName: "pym_u_id",
  orderPaymentMethodLabelName: "Payment Method",
  orderPaymentMethodReqMsg: "Payment Method is required",

  orderBankFieldName: "bnk_u_id",
  orderBankLabelName: "Bank",
  orderBankReqMsg: "Bank is required",

  orderTaxFieldName: "tax_u_id",
  orderTaxLabelName: "Tax",
  orderTaxReqMsg: "Tax is required",

  orderProductFieldName: "product_id",
  orderProductLabelName: "Product",
  orderProductReqMsg: "Product is required",

  orderQuantityFieldName: "quantity",
  orderQuantityLabelName: "Quantity",
  orderQuantityReqMsg: "Quantity is required",

  orderAddCustomerTitle: "Customer",
  orderAddProductTitle: "Product",
  orderAddAddressTitle: "Address",
  orderAddPaymentTitle: "Payment",
  orderAddConfirmationsTitle: "Confirmations",

  orderStepAddressCustomerTitle: "Customer Address",
  orderStepAddressAddNewAddressButton: "Add new address",
  orderStepAddressDialogContentText: "Add Customer Address",

  orderStepAddressCustomerName: "Customer Name",
  orderStepAddressCustomerFieldName: "cus_u_id",

  orderStepAddressAddressTypeName: "Address Type",
  orderStepAddressAddressTypeFieldName: "address_type",
  orderStepAddressAddressTypeBilling: "Billing",
  orderStepAddressAddressTypeShipping: "Shipping",

  orderStepAddressAddressName: "address",
  orderStepAddressAddressLabelName: "Address",
  orderStepAddressAddressPlaceholder: "Enter Your Address",
  orderStepAddressIsDefault: "is_default",

  orderStepAddressCustomRadiosAddress: "custom-radios-address",
  orderStepAddressCustomRadiosDelivery: "custom-radios-delivery",
  orderStepAddressEstimatedDeliveryDate: "Estimated Delivery Date",
  orderStepAddressGoogleHomeWhite: "Google - Google Home - White",
  orderStepAddressDateText: "18th Nov 2021",

  orderStepCustomerTitle: "Search Customer",

  orderStepCustomerFirstName: "first_name",
  orderStepCustomerFirstNameReqMsg: "First Name is required",
  orderStepCustomerFirstNameMsg: "Last Name must be minimum 3 characters",
  orderStepCustomerNameMessage: "Only alphabets allowed",
  orderStepCustomerSearchDetails: "Search customer details",
  orderStepCustomerLabelName: "Customer Name",
  orderStepCustomerFirstNamePlaceholder: "Ranbir",

  orderStepCustomerLastName: "last_name",
  orderStepCustomerLastNameReqMsg: "Last Name is required",
  orderStepCustomerLastNameMsg: "Last Name must be minimum 3 characters",
  orderStepCustomerLastLabelName: "Last Name",
  orderStepCustomerLastNamePlaceholder: "Patel",

  orderStepCustomerPhone: "phone",
  orderStepCustomerPhoneReqMsg: "Phone No is required",
  orderStepCustomerPhoneLabelName: " Phone Number",
  orderStepCustomerPhonePlaceholder: "9876543210",

  orderStepCustomerAlternateNumberName: "alternate_phone",
  orderStepCustomerAlternateNumberLabelName: " Alternate Number",
  orderStepCustomerAlternateNumberPlaceholder: "9876543210",

  orderStepCustomerEmailName: "email",
  orderStepCustomerEmailReqMsg: "Email is required",
  orderStepCustomerEmailMsg: "Email is Not Valid",
  orderStepCustomerEmailLabelName: "Email",
  orderStepCustomerEmailPlaceholder: "ranbir@gmail.com",

  orderStepCustomerCustomerTypeName: "customer_type",
  orderStepCustomerCustomerTypeReqMsg: "Customer Type is required",
  orderStepCustomerCustomerTypeLabelName: "Customer Type",
  orderStepCustomerResidential: "Residential",
  orderStepCustomerCommercial: "Commercial",

  orderStepPaymentCardLabel: "Card",
  orderStepPaymentCashOnDeliveryLabel: "Cash On Delivery",
  orderStepPaymentBankTransferLabel: "Bank Transfer",
  orderStepPaymentNetBankingLabel: "Net Banking",
  orderStepPaymentUPILabel: "UPI",
  orderStepPaymentQRCodeLabel: "QR Code",

  orderStepPaymentTransactionIDLabel: "Transaction ID",
  orderStepPaymentTransactionIDPlaceholder: "xxxx-xxxx-xx-xx",

  orderStepPaymentFutureBillingLabel: "Save Card for future billing?",
  orderStepPaymentCheckoutButton: "Checkout",
  orderStepPaymentResetButton: "Reset",

  orderStepPaymentBankTitle: "Enter Bank Details",

  orderStepPaymentNameLabel: "Name",
  orderStepPaymentNamePlaceholder: "Enter Name",

  orderStepPaymentBranchLabel: "Branch",
  orderStepPaymentBranchPlaceholder: "Enter Branch",

  orderStepPaymentAccountNumberLabel: "Account Number",
  orderStepPaymentAccountNumberPlaceholder: "xxxx-xxxx-xx-xx",

  orderStepPaymentIFSCCodeLabel: "IFSC Code",
  orderStepPaymentIFSCCodePlaceholder: "xxxxxxx",

  orderStepProductSearchText: "Search Product",
  orderStepProductFieldName: "name",
  orderStepProductName: "Product Name",
  orderStepProductHSNCodeField: "hsn_code",
  orderStepProductHSNCode: "HSN Code",
  orderStepProductSKUCodeField: "sku_code",
  orderStepProductSKUCode: "SKU Code",
  orderStepProductSellingPriceField: "sell_price",
  orderStepProductSellingPrice: "Selling Price",
  orderStepProductStockField: "stock",
  orderStepProductStock: "Stock",
  orderStepProductAddText: "  Add Product",
  orderStepProductPlaceOrderButton: " Place Order",
  orderStepProductListText: "Product List",

  // Target
  addNewTarget: "Add New Target",
  employeeNameFieldTarget: "employeename",
  employeeNameHeaderTarget: "Employee Name",
  addProductTargetTitle: "Add Product Target",
  selectCategoryTarget: "Select Category",
  selectCategoryName: "category",
  targetCategoryRequired: "Category is required",
  selectProductTarget: "Select Product",
  selectProductName: "product",
  targetProductRequired: "Product is required",
  addSellingTargetTitle: "Add Selling Target",
  sellingTargetDescriptionName: "description",
  sellingTargetDescriptionLabel: "Description",
  sellingTargetDescriptionRequired: "Description is required",
  targetQuantityName: "targetQuantity",
  targetQuantityLabel: "Target Quantity",
  targetQuantityRequired: "Target Quantity is required",
  addMonthlyTarget: "Add Monthly Target",
  sellingTargetLabel: "Selling Target",
  productTargetLabel: "Product Target",
  searchProductTarget: "Search Product",
  addProductTarget: "Add Product",
  productFieldNameTarget: "productname",
  productHeaderNameTarget: "Product Name",
  categoryFieldNameTarget: "categoryname",
  categoryHeaderNameTarget: "Category Name",
  sellingTargetPlaceholder: "Search",
  quantityFieldNameTarget: "quantity",
  quantityHeaderNameTarget: "Quantity",
  soldFieldNameTarget: "soldquantity",
  soldHeaderNameTarget: "Sold Quantity",
  remainingQuantityFieldNameTarget: "remainingquantity",
  remainingQuantityHeaderNameTarget: "Remaining",
  sellingTargetListTitle: "Selling Target List",
  createTargetCategory: "Create target",
  targetNewTargetBrandFieldName: "brand_id",
  targetNewTargetBrandLabelName: "Brand",
  targetNewTargetBrandReqMsg: "Brand is required",
  targetNewTargetCategoryFieldName: "category_id",
  targetNewTargetCategoryLabelName: "Category",
  targetNewTargetCategoryReqMsg: "Category is required",
  targetNewTargetProductFieldName: "product_id",
  targetNewTargetProductLabelName: "Product",
  targetNewTargetProductReqMsg: "Product is required",
  targetNewTargetSalesmanFieldName: "dcs_u_id",
  targetNewTargetSalesmanLabelName: "Salesman",
  targetNewTargetSalesmanReqMsg: "Salesman is required",
  targetNewTargetTotalTargetFieldName: "selling_target",
  targetNewTargetTotalTargetLabelName: "Selling Target",
  targetNewTargetTotalTargetReqMsg: "Total Target is required",
  targetNewTargetTotalTargetPlaceholder: "Enter Total Target",
  targetNewTargetSalesmanLabelNameList: "Salesman Name",
  targetNewTargetBrandLabelNameList: "Brand Name",
  targetNewTargetCategoryLabelNameList: "Category Name",
  targetNewTargetProductLabelNameList: "Product Name",
  targetNewTargetSellingTargetLabelNameList: "Selling Target",
  targetNewTargetBrandFieldNameList: "brand_name",
  targetNewTargetSalesmanFieldNameList: "staff_name",
  targetNewTargetCategoryFieldNameList: "category_name",
  targetNewTargetProductFieldNameList: "product_name",

  // Service/Installation
  serviceSearch: "Search",
  serviceCustomerFieldName: "name",
  serviceCustomerHeaderName: "Customer Name",
  servicePhoneFieldName: "phone",
  servicePhoneHeaderName: "Phone",
  serviceAlternatePhoneFieldName: "alternate_phone",
  serviceAlternatePhoneHeaderName: "Alternate Phone",
  serviceAddressFieldName: "address",
  serviceAddressHeaderName: "Address",
  servicePreferredDateFieldName: "preferred_date",
  servicePreferredDateHeaderName: "Preferred Date",
  servicePreferredTimeFieldName: "preferred_time",
  servicePreferredTimeHeaderName: "Preferred Time",
  serviceServiceDateFieldName: "service_date",
  serviceServiceDateHeaderName: "Service Date",
  serviceServiceTypeFieldName: "service_type",
  serviceServiceTypeHeaderName: "Service Type",
  serviceCustomerNotesFieldName: "customer_notes",
  serviceCustomerNotesHeaderName: "Customer Notes",
  serviceTechnicianNotesFieldName: "technician_notes",
  serviceTechnicianNotesHeaderName: "Technician Notes",
  serviceErrorId: "Service with the id:",
  serviceErrorMessage: "does not exist. Please check the list of services:",
  serviceNameTitle: "Name:",
  serviceAddressTitle: "Address:",
  serviceMobileNoTitle: "Mobile No.:",
  serviceAlternateMobileNoTitle: "Alternate Mobile No.:",
  serviceStatusTitle: "Status:",
  servicePreferredDateTitle: "Preferred Date:",
  servicePreferredTimeTitle: "Preferred Time:",
  serviceServiceDateTitle: "Service Date:",
  serviceServiceTimeTitle: "Service Time:",
  serviceServiceTypeTitle: "Service Type:",
  serviceCustomerNotesTitle: "Customer Notes:",
  serviceTechnicianNotesTitle: "Technician Notes:",
  serviceListTitle: "Service List",

  installationDateFieldName: "installation_date",
  installationDateHeaderName: "Installation Date",
  installationWarrantyStartDateFieldName: "warranty_start_date",
  installationWarrantyStartDateHeaderName: "Warranty Start Date",
  installationWarrantyEndDateFieldName: "warranty_end_date",
  installationWarrantyEndDateHeaderName: "Warranty End Date",
  installationAddressFieldName: "address",
  installationAddressHeaderName: "Address",
  installationErrorId: "Installation with the id:",
  installationErrorMessage:
    "does not exist. Please check the list of Installations:",
  installationListTitle: "Installation List",

  installationOrderIdLabel: "Order ID",
  installationInstallationDateLabel: "Installation Date",
  installationWarrantyStartDateLabel: "Warranty Start Date",
  installationWarrantyEndDateLabel: "Warranty End Date",

  roomNoLabel: "Rooms No.",
  roomConfig: "RoomConfig",
  roomDetailsLabel: "Room Details",
  extraParts: "Extra Parts:",
  productNameLabel: "Product Name:",
  totalProduct: "Total Product:",

  // Task
  taskAddTitleText: "Add Task",
  taskFieldNameText: "task",
  taskLabelNameText: "Task",
  taskStaffFieldNameText: "first_name",
  taskStaffLabelNameText: "Full Name",
  taskDateFieldText: "date",
  taskDateNameText: "Date",
  taskPreferredDateFieldText: "preferred_date",
  taskPreferredDateText: "Preferred Date",
  taskPreferredTimeFieldText: "preferred_time",
  taskPreferredTimeText: "Preferred Time",
  taskCustomerReasonFieldText: "customer_reason",
  taskCustomerReasonText: "Customer Reason",
  taskStaffReasonFieldText: "staff_reason",
  taskStaffReasonText: "Staff Reason",
  taskStatusFieldText: "status",
  taskStatusNameText: "Status",
  taskActionsFieldText: "actions",
  taskActionsNameText: "Actions",
  taskNameReqMsg: "Task is required",
  taskDateNameReqMsg: "Date is required",
  taskStaffFieldName: "dcs_u_id",
  taskStaffLabelName: "Staff",
  taskOrderFieldName: "ord_u_id",
  taskOrderLabelName: "Order",
  taskOrderNameReqMsg: "Order is required",
  taskAssignedToFieldName: "assigned_to",
  taskAssignedToLabelName: "Assigned To",
  taskReasonToAssignToFieldName: "reason_to_assign",
  taskReasonToAssignLabelName: "Reason To Assign",
  taskServiceFieldName: "srv_u_id",
  taskServiceLabelName: "Service",
  taskServiceNameReqMsg: "Task is required",
  taskFieldNameServices: "services",
  taskFieldNameInstallation: "installation",

  // General-task
  generalTaskAddTitle: " Add Task",
  generalTaskTitle: "General Task",
  generalTaskStaffFieldName: "staff_name",
  generalTaskStaffLabelName: "Staff Name",
  generalTaskRoleFieldName: "role_name",
  generalTaskRoleLabelName: "Role Name",
  generalTaskFieldTask: "task",
  generalTaskLabelTask: "Task",
  generalTaskFieldAssignDate: "assign_date",
  generalTaskLabelAssignDate: "Assign Date",
  generalTaskFieldCompletionDate: "completion_date",
  generalTaskLabelCompletionDate: "Completion Date",
  generalTaskFieldStatus: "status",
  generalTaskLabelStatus: "Status",
  generalTaskLabelStatusReqMsg: "Status Type is required",
  generalTaskLabelPendingText: "Pending",
  generalTaskLabelCompletedText: "Completed",
  generalTaskAddTitleDetails: "Add Task Details",
  generalTaskRoleFieldNameID: "rol_u_id",
  generalTaskSelectRoleLabel: "Select Role",
  generalTaskSelectRoleLabelReqMsg: "role is required",
  generalTaskStaffFieldNameID: "dcs_u_id",
  generalTaskSelectStaffLabel: "Select Staff",
  generalTaskSelectStaffLabelReqMsg: "staff is required",
  generalTaskFieldTaskReqMsg: "task is required",
  generalTaskLabelTaskTitle: "Task Title",
  generalTaskLabelTaskTitlePlaceholder: "Enter Task Title",
  generalTaskFieldDescription: "description",
  generalTaskFieldDescriptionReqMsg: "description is required",
  generalTaskLabelDescriptionTitle: "Task Description",
  generalTaskLabelDescriptionTitlePlaceholder: "Enter description",
  generalTaskFieldStaffNote: "res_note",
  generalTaskFieldStaffNoteReqMsg: "staff note is required",
  generalTaskLabelStaffNoteTitle: "Staff Note",
  generalTaskLabelStaffNoteTitlePlaceholder: "Enter staff note",
};
